/**
 * Fetches the local surah index generated by the backend during startup.
 * Runs instantly client-side.
 */
export async function fetchSurahIndex() {
  try {
    const res = await fetch("/surah_index.json");
    if (!res.ok) throw new Error("Failed to load Surah index");
    return await res.json();
  } catch (error) {
    console.error("Error loading Surah index:", error);
    return [];
  }
}

/**
 * Filters the list of surahs based on the user's search query.
 * Matches against surah number, English name, and Arabic name.
 */
export function filterSurahs(query, surahList) {
  if (!query) return surahList;
  
  const lowerQuery = query.toLowerCase().trim();
  
  return surahList.filter(surah => {
    return (
      surah.number.toString() === lowerQuery ||
      surah.nameSimple.toLowerCase().includes(lowerQuery) ||
      surah.nameArabic.includes(lowerQuery)
    );
  });
}
