import { surahMeanings } from './surah_meanings';

/**
 * Fetches the local surah index generated by the backend during startup.
 * Runs instantly client-side.
 */
export async function fetchSurahIndex() {
  try {
    const res = await fetch("/surah_index.json");
    if (!res.ok) throw new Error("Failed to load Surah index");
    return await res.json();
  } catch (error) {
    console.error("Error loading Surah index:", error);
    return [];
  }
}

/**
 * Normalizes text for search matching by lowercasing, trimming,
 * and stripping hyphens, apostrophes, and spaces.
 */
function normalizeSearchText(text) {
  if (!text) return "";
  return text.toLowerCase().trim().replace(/[-'\s]/g, "");
}

const SEARCH_ALIASES = {
  "yaseen": 36,
};

/**
 * Filters the list of surahs based on the user's search query.
 * Matches against surah number, English name, and Arabic name.
 */
export function filterSurahs(query, surahList) {
  if (!query) return surahList;
  
  const normalizedQuery = normalizeSearchText(query);
  const trimmedQuery = query.trim();
  const aliasSurahId = SEARCH_ALIASES[normalizedQuery];
  
  return surahList.filter(surah => {
    return (
      (aliasSurahId && surah.number === aliasSurahId) ||
      surah.number.toString().startsWith(trimmedQuery) ||
      normalizeSearchText(surah.nameSimple).includes(normalizedQuery) ||
      normalizeSearchText(surahMeanings[surah.number]).includes(normalizedQuery) ||
      surah.nameArabic.includes(trimmedQuery)
    );
  });
}
